name: "Build"

on:
  workflow_dispatch:    
    branches: [main]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
       - name: check Xcode version
         run: /usr/bin/xcodebuild -version
       - name: checkout repository
         uses: actions/checkout@v3
       - name: build iOS
         run: |
           cd litehtml-maui-native
           ./build_ios.sh
       - name: Upload a Build Artifact
         uses: actions/upload-artifact@v3.2.1-node20
         with:
           # Artifact name
           name: ioslib
           # A file, directory or wildcard pattern that describes what to upload
           path: ../LiteHtmlMaui/Platforms/iOS/NativeLibs/*.a
          
